name: safe_solutions
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.4
  auto_size_text: ^3.0.0
  font_awesome_flutter: 10.4.0
  intl: 0.20.2
  go_router: ^12.1.3
  rxdart: ^0.27.7
  dio: ^5.3.2
  collection: ^1.17.0
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true